### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by zhao23000** [Luoyuhao12345/mpc_diff_wheeled#1]
你好，我编译后运行my_gazebo_rviz.launch时报错，说cannot launch node of type [my_planner/path_generate.py]，界面上也，没有归经济，请问这个怎么解决呀

**Comment by Luoyuhao12345** [comment]
检查一下py文件的属性有没有被设置成可执行文件



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月5日(Sun) AM10:39
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Luoyuhao12345/mpc_diff_wheeled] 运行问题 (Issue #1)




 
你好，我编译后运行my_gazebo_rviz.launch时报错，说cannot launch node of type [my_planner/path_generate.py]，界面上也，没有归经济，请问这个怎么解决呀
